export const RUNTIME_ENV = Object.freeze({
  APP_HOST: "127.0.0.1",
  APP_PORT: "8080",
  MOODLE_ASSET_BASE_URL: "./vendor/moodle",
  MOODLE_AVAILABLE_VERSIONS: "4.3,4.4",
  MOODLE_ADMIN_USER: "admin",
  MOODLE_DB_HOST: "idb-storage",
  MOODLE_DB_NAME: "moodle",
  MOODLE_DB_PASSWORD: "postgres",
  MOODLE_DB_PREFIX: "mdl_",
  MOODLE_DB_USER: "postgres",
  MOODLE_DEFAULT_VERSION: "4.4",
  MOODLE_MANIFEST_URL: "./vendor/moodle/4.4/manifest.json",
  PHP_WASM_VERSION: "0.0.9-alpha-32",
  PYTHON_BIN: "python3",
});
